# Generated by Django 4.2.2 on 2023-06-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_departmentmodel_code'),
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher', to='authentication.teachermodel'),
        ),
    ]
