# Generated by Django 4.2.2 on 2023-07-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeelectivemodel',
            name='teacher_1_approval',
        ),
        migrations.RemoveField(
            model_name='changeelectivemodel',
            name='teacher_2_approval',
        ),
        migrations.AddField(
            model_name='changeelectivemodel',
            name='teacher_1_decision',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default=('PENDING', 'PENDING'), max_length=10),
        ),
        migrations.AddField(
            model_name='changeelectivemodel',
            name='teacher_2_decision',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default=('PENDING', 'PENDING'), max_length=10),
        ),
    ]
