# Generated by Django 4.2.2 on 2023-07-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactUsModel',
        ),
    ]
