# Generated by Django 4.2.2 on 2023-06-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enollmentmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='enollmentmodel',
            name='subject_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_subject_1', to='app.subjectmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enollmentmodel',
            name='subject_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_subject_2', to='app.subjectmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enollmentmodel',
            name='subject_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_subject_3', to='app.subjectmodel'),
            preserve_default=False,
        ),
    ]
