# Generated by Django 4.2.2 on 2023-06-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_departmentmodel_studentmodel_department_and_more'),
        ('app', '0003_remove_enollmentmodel_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='department_subject', to='authentication.departmentmodel'),
            preserve_default=False,
        ),
    ]
