# Generated by Django 4.2.2 on 2023-06-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_enollmentmodel_subject_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeelectivemodel',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
