# Generated by Django 4.2.2 on 2023-06-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_departmentmodel_studentmodel_department_and_more'),
        ('app', '0004_subjectmodel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher', to='authentication.teachermodel'),
        ),
    ]
