# Generated by Django 4.2.2 on 2023-06-14 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('app', '0004_changeelectivemodel_is_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enollmentmodel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='authentication.studentmodel'),
        ),
    ]
