# Generated by Django 4.2.2 on 2023-06-14 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('app', '0005_alter_enollmentmodel_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher', to='authentication.teachermodel'),
        ),
    ]
