# Generated by Django 4.2.2 on 2023-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subjectmodel_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='subject'),
        ),
    ]
