# Generated by Django 4.2.2 on 2023-06-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_studentmodel_profile_pic'),
        ('app', '0006_subjectmodel_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enollmentmodel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.studentmodel'),
        ),
    ]
