# Generated by Django 4.2.2 on 2023-06-13 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_teachermodel_profile_pic'),
        ('app', '0007_alter_enollmentmodel_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeElectiveModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_1_approval', models.BooleanField(default=False)),
                ('teacher_2_approval', models.BooleanField(default=False)),
                ('from_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_subject', to='app.subjectmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_change_elective', to='authentication.studentmodel')),
                ('to_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_subject', to='app.subjectmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
