# Generated by Django 4.2.2 on 2023-06-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contactus_alter_subjectmodel_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='intro',
            field=models.URLField(default='https://youtu.be/Fw-S8NCDsTY'),
        ),
    ]
