# Generated by Django 4.2.2 on 2023-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='teacher'),
            preserve_default=False,
        ),
    ]
