# Generated by Django 4.2.2 on 2023-06-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_departmentmodel_studentmodel_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='student'),
        ),
    ]
