# Generated by Django 4.2.2 on 2023-06-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_departmentmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
