# Generated by Django 4.2.2 on 2023-06-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_teachermodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='experience',
            field=models.FloatField(default=1.0),
        ),
    ]
