# Generated by Django 4.2.2 on 2023-06-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_teachermodel_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='time_table',
            field=models.ImageField(blank=True, null=True, upload_to='time-table'),
        ),
    ]
