# Generated by Django 4.2.2 on 2023-06-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_departmentmodel_time_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_department', to='authentication.departmentmodel'),
        ),
    ]
