# Generated by Django 4.2.2 on 2023-06-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
